# Generated by Django 3.1.7 on 2021-03-24 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='station-id')),
                ('label', models.CharField(max_length=40, verbose_name='station-label')),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='create-date')),
                ('time', models.TimeField(verbose_name='create-time')),
                ('speed', models.FloatField(verbose_name='wind-speed')),
                ('direction', models.CharField(max_length=10, verbose_name='wind-direction')),
                ('temperature', models.FloatField(verbose_name='temperature')),
                ('humidity', models.FloatField(verbose_name='humidity')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station.station')),
            ],
        ),
    ]
